# Generated by Django 2.2.9 on 2021-02-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_group_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Group',
            new_name='group',
        ),
        migrations.RemoveField(
            model_name='group',
            name='name',
        ),
        migrations.AddField(
            model_name='group',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
