# Generated by Django 2.2.9 on 2021-02-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210218_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.CharField(default='', max_length=200),
        ),
    ]
