# Generated by Django 2.2.9 on 2021-02-24 10:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20210224_1334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disk',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='disk',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date requested'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disk',
            name='new_request',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
