# Generated by Django 2.2.9 on 2021-03-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.CharField(help_text='Текст комменатрия', max_length=100),
        ),
    ]
