# Generated by Django 2.2.9 on 2021-02-24 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Disk',
        ),
    ]
